{"type":"settings","kernel":"python2","backend_state":"running","trust":true,"metadata":{"language_info":{"codemirror_mode":{"name":"ipython","version":2},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython2","version":"2.7.13"}},"kernel_usage":{"cpu":0,"memory":79839232},"kernel_state":"idle"}
{"type":"file","last_load":1511221541757}
{"type":"cell","id":"519a18","pos":55,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,-pi/2.0,-pi/3.0),ylim=[-10.0,-0.5],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"59baae","pos":59,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,-pi/6.0,0.0),ylim=[-2.5,0.5],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"1720aa","pos":60,"input":"# $\\lbrack0,\\pi/6\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"6c6b1d","pos":50,"input":"We can plot all of them on the same graph to see which graph fits the best.","cell_type":"markdown"}
{"type":"cell","id":"5ee0ed","pos":39,"input":"for p in myE:\n    print p","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"feeeb6","pos":13,"input":"myplot=plot(sin(x),u11,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"image/png":"cb4516992983acd7f073d3f37998d92bdb07c0e4"}}},"cell_type":"code","exec_count":11}
{"type":"cell","id":"9b55f3","pos":72,"input":"U1 has an advantage at the negative x-axis from $-pi/2$ to $0$. It also is almost exactly approximates $\\sin(t)$ at the zero point. From $0$ to $pi/6$ U5 has an advantage. From $pi/6$ to $pi/3$ U2 has a good approximation. From $pi/3$ to $pi/2$ U2 and U5 are both closest to the red line of $\\sin(t)$. From $pi/2$ to $2pi/3$ U3 and U6 are closest. From $2pi/3$ to $pi$ U6 is a very good approximation to the $\\sin(t)$.","cell_type":"markdown"}
{"type":"cell","id":"b1a47d","pos":36,"input":"import scipy.integrate as integrate","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"b9dde0","pos":2,"input":"We need to find a cubic polynomial $u$ that best approximates sin(t) in the sense that \n\\begin{equation}\n||u(t)-sin(t)||\n\\end{equation}\nis minimized.","cell_type":"markdown"}
{"type":"cell","id":"2135e6","pos":12,"input":"u11=0\nfor p in myE:\n    u11+= u1(sin(x),p) * p\nprint u11","output":{"0":{"name":"stdout","output_type":"stream","text":"0.0570363551680557*x**3 - 0.516646339291639*x**2 + 1.00000000000001*x + 9.99200722162641e-16\n"}},"cell_type":"code","exec_count":10}
{"type":"cell","id":"47c262","pos":7,"input":"x = Symbol('x')","cell_type":"code","exec_count":4}
{"type":"cell","id":"b05797","pos":35,"input":"# U5\n\\begin{align*}\n \\langle f,g\\rangle_5&=\\int_0^6 f(t)g(t)dt \\\\\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"73880d","pos":22,"input":"myplot=plot(sin(x),u12,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"image/png":"949f10646fa9914f0b3d5986da4deea70fc85d5a"}}},"cell_type":"code","exec_count":17}
{"type":"cell","id":"38cbb5","pos":24,"input":"def u3(f,g):\n    return f.subs(x,0.0)*g.subs(x,0.0)+f.subs(x,2.0)*g.subs(x,2.0)+f.subs(x,4.0)*g.subs(x,4.0)+f.subs(x,6.0)*g.subs(x,6.0)","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"b541be","pos":41,"input":"myplot=plot(sin(x),u15,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"cc60c7","pos":1,"input":"# Approximate the sine in six ways","cell_type":"markdown"}
{"type":"cell","id":"816d06","pos":9,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u1(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u1(fi,fi))))","cell_type":"code","exec_count":6}
{"type":"cell","id":"4679e5","pos":21,"input":"u12=0\nfor p in myE:\n    u12+= u2(sin(x),p) * p\nprint u12","output":{"0":{"name":"stdout","output_type":"stream","text":"0.10776013256668*x**3 - 1.00192120815073*x**2 + 2.22086432446957*x - 0.485232264077618\n"}},"cell_type":"code","exec_count":16}
{"type":"cell","id":"081633","pos":73,"input":"In conclusion, we believe that around zero U1 has the best approximation, at around $pi$ U6 is the best approximation, and in between them U2 is the best approximation.","cell_type":"markdown"}
{"type":"cell","id":"cf81e1","pos":69,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,2.0*pi/3.0,5.0*pi/6.0),ylim=[0.2,0.8],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"a6dd3d","pos":61,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,0.0,pi/6.0),ylim=[-2.5,1.0],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"9f209e","pos":28,"input":"myplot=plot(sin(x),u13,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"881fed","pos":5,"input":"# U1\n\\begin{align*}\n\\langle f,g\\rangle_1&=f(0)g(0)+f'(0)g'(0)+f(6)g(6)+f'(6)g'(6)\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"e7107a","pos":16,"input":"<span style=\"color:red\">You see, the values of the function and their derivatives match at zero and six.\n</span>","cell_type":"markdown"}
{"type":"cell","id":"6ca914","pos":29,"input":"# U4\n\\begin{align*}\n \\langle f,g\\rangle_4&=f(0)g(0)+f(3)g(3)+f'(3)g'(3)+f(6)g(6)\\\\\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"548958","pos":45,"input":"for p in myE:\n    print p","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"47f66f","pos":62,"input":"# $\\lbrack \\pi/6,\\pi/3\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"faff75","pos":67,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,pi/2.0,2.0*pi/3.0),ylim=[0.8,1.2],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"d2263f","pos":15,"input":"myplot=plot(sin(x),u11,(x,-0.5,6.5),ylim=[-1.5,1.5],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"image/png":"bf7b9eef1e4d3bef99c4a11853e32312038146c6"}}},"cell_type":"code","exec_count":12}
{"type":"cell","id":"0987a8","pos":63,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,pi/6.0,pi/3.0),ylim=[-1.0,1.5],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"f35bce","pos":58,"input":"# $\\lbrack-\\pi/6,0\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"a16b12","pos":25,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u3(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u3(fi,fi))))","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"f352a0","pos":70,"input":"# $\\lbrack 5\\pi/6,\\pi\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"c5627c","pos":20,"input":"for p in myE:\n    print p","output":{"0":{"name":"stdout","output_type":"stream","text":"sqrt(2)/2\n0.316227766016838*x - 0.948683298050514\n0.176776695296637*x**2 - 1.06066017177982*x + 0.883883476483185\n0.0988211768802619*x**3 - 0.889390591922356*x**2 + 2.1147731852376*x - 1.00797600417867\n"}},"cell_type":"code","exec_count":15}
{"type":"cell","id":"038846","pos":44,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u6(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u6(fi,fi))))","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"459ba6","pos":18,"input":"def u2(f,g):\n    df = f.diff(x)\n    dg = g.diff(x)\n    return f.subs(x,1.0)*g.subs(x,1.0)+df.subs(x,1.0)*dg.subs(x,1.0)+f.subs(x,5.0)*g.subs(x,5.0)+df.subs(x,5.0)*dg.subs(x,5.0)","cell_type":"code","exec_count":13}
{"type":"cell","id":"c44a0a","pos":8,"input":"def u1(f,g):\n    df = f.diff(x)\n    dg = g.diff(x)\n    return f.subs(x,0.0)*g.subs(x,0.0)+df.subs(x,0.0)*dg.subs(x,0.0)+f.subs(x,6.0)*g.subs(x,6.0)+df.subs(x,6.0)*dg.subs(x,6.0)","cell_type":"code","exec_count":5}
{"type":"cell","id":"4d6cce","pos":49,"input":"By looking at the graphs we can see how well each of the cubic polynomial approximations works to fit to the sin(t) function.","cell_type":"markdown"}
{"type":"cell","id":"77c53c","pos":57,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,-pi/3.0,-pi/6.0),ylim=[-3.5,-0.5],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"be2a22","pos":0,"input":"# Gram Schmidt Process","cell_type":"markdown"}
{"type":"cell","id":"5d96ef","pos":64,"input":"# $\\lbrack \\pi/3,\\pi/2\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"7001e8","pos":65,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,pi/3.0,pi/2.0),ylim=[0.5,1.5],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"b10a9c","pos":3,"input":"Let us find $u_1$, $u_2$, $u_3$, $u_4$, $u_5$, $u_6$ and plot the results to compare them.","cell_type":"markdown"}
{"type":"cell","id":"01162a","pos":51,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"187b26","pos":32,"input":"for p in myE:\n    print p","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"6aa14f","pos":40,"input":"u15=0\nfor p in myE:\n    u15+= u5(sin(x),p) * p\nprint u15","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"8b9726","pos":46,"input":"u16=0\nfor p in myE:\n    u16+= u6(sin(x),p) * p\nprint u16","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"801e4e","pos":10,"input":"for p in myE:\n    print p","output":{"0":{"name":"stdout","output_type":"stream","text":"sqrt(2)/2\n0.223606797749979*x - 0.670820393249937\n0.117851130197758*x**2 - 0.707106781186547*x\n0.0414086662499961*x**3 - 0.372677996249966*x**2 + 0.670820393249943*x + 0.22360679774998\n"}},"cell_type":"code","exec_count":9}
{"type":"cell","id":"9fb3d3","pos":14,"input":"## <span style=\"color:red\">Terilla</span>\n<span style=\"color:red\">Here, it's much better to look at the picture on an interval containing $[0,6]$.  Consideration of your inner product $\\langle \\, \\rangle_1$ suggests that $u_1$ and $\\sin$ will match up very well at $x=0$ and $x=6$.  Look:\n</span>","cell_type":"markdown"}
{"type":"cell","id":"407f10","pos":66,"input":"# $\\lbrack \\pi/2,2\\pi/3\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"3d0d6d","pos":38,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u5(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u5(fi,fi))))","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"f5eb3f","pos":54,"input":"# $\\lbrack-\\pi/2,-\\pi/3\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"3b1009","pos":30,"input":"def u4(f,g):\n    df = f.diff(x)\n    dg = g.diff(x)\n    return f.subs(x,0.0)*g.subs(x,0.0)+f.subs(x,3.0)*g.subs(x,3.0)+df.subs(x,3.0)*dg.subs(x,3.0)+f.subs(x,6.0)*g.subs(x,6.0)","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"795367","pos":11,"input":"Now, we orthogonally project sin(x) onto U.","cell_type":"markdown"}
{"type":"cell","id":"0ef5b4","pos":48,"input":"# Conclusion","cell_type":"markdown"}
{"type":"cell","id":"73885e","pos":26,"input":"for p in myE:\n    print p","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"281b43","pos":17,"input":"# U2\n\\begin{align*}\n\\langle f,g\\rangle_2&=f(1)g(1)+f'(1)g'(1)+f(5)g(5)+f'(5)g'(5)\\\\\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"7ed851","pos":27,"input":"u13=0\nfor p in myE:\n    u13+= u3(sin(x),p) * p\nprint u13","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"e79699","pos":31,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u4(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u4(fi,fi))))","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"f9565f","pos":43,"input":"def u6(f,g):\n    df = f.diff(x)\n    dg = g.diff(x)\n    df2 = df.diff(x)\n    dg2 = dg.diff(x)\n    df3 = df2.diff(x)\n    dg3 = dg2.diff(x)\n    return f.subs(x,3.0)*g.subs(x,3.0)+df.subs(x,3.0)*dg.subs(x,3.0)+df2.subs(x,3.0)*dg2.subs(x,3.0)+df3.subs(x,3.0)*dg3.subs(x,3.0)","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"526913","pos":68,"input":"# $\\lbrack 2\\pi/3,5\\pi/6\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"5cf4f8","pos":6,"input":"from sympy import *","cell_type":"code","exec_count":3}
{"type":"cell","id":"0f5f4d","pos":4,"input":"import numpy as np","cell_type":"code","exec_count":2}
{"type":"cell","id":"f8fc39","pos":42,"input":"# U6\n\\begin{align*}\n\\langle f,g\\rangle_6&=f(3)g(3)+f'(3)g'(3)+f''(3)g''(3)+f'''(3)g'''(3)\\\\\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"9c2efc","pos":34,"input":"myplot=plot(sin(x),u14,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"f1612e","pos":37,"input":"def u5(f,g):\n    h=f*g;\n    return integrate.quad(lambda t: h.subs(x,t),0.0,6.0)[0]","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"84915b","pos":33,"input":"u14=0\nfor p in myE:\n    u14+= u4(sin(x),p) * p\nprint u14","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"513531","pos":47,"input":"myplot=plot(sin(x),u16,(x,-4,4),ylim=[-4,4],show=False)\nmyplot[0].line_color = 'r'\nmyplot[1].line_color = 'g'\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"fe55c2","pos":23,"input":"# U3\n\\begin{align*}\n \\langle f,g\\rangle_3&=f(0)g(0)+f(2)g(2)+f(4)g(4)+f(6)g(6)\\\\\n\\end{align*}","cell_type":"markdown"}
{"type":"cell","id":"fd85e1","pos":52,"input":"We can look at the graphs closer to see which approximates sin(t) the best. Let us make make graphs at different intervals to see which approximation is the best at which interval. For instance, we are going to use 9 intervals from $-\\pi/2$ to $\\pi$ in steps of $\\pi/6$ like this:\n$\\lbrack-\\pi/2,-\\pi/3\\rbrack$,\n$\\lbrack-\\pi/3,-\\pi/6\\rbrack$,\n$\\lbrack-\\pi/6,0\\rbrack$,\n$\\lbrack0,\\pi/6\\rbrack$,\n$\\lbrack \\pi/6,\\pi/3\\rbrack$,\n$\\lbrack \\pi/3,\\pi/2\\rbrack$,\n$\\lbrack \\pi/2,2\\pi/3\\rbrack$,\n$\\lbrack 2\\pi/3,5\\pi/6\\rbrack$,\n$\\lbrack 5\\pi/6,\\pi\\rbrack$.","cell_type":"markdown"}
{"type":"cell","id":"d6bc8d","pos":53,"input":"from math import pi","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}
{"type":"cell","id":"9de5ad","pos":56,"input":"# $\\lbrack-\\pi/3,-\\pi/6\\rbrack$","cell_type":"markdown"}
{"type":"cell","id":"f46362","pos":19,"input":"k = 3 # max degree\nmyE = [] # initialize the output with zeros\nfor i in range(k+1):\n    fi=x**i\n    for j in range(i):\n        fi+=-u2(myE[j],x**i)*myE[j]\n    myE.append(fi/(sqrt(u2(fi,fi))))","cell_type":"code","exec_count":14}
{"type":"cell","id":"1d7207","pos":71,"input":"myplot=plot(sin(x),u11,u12,u13,u14,u15,u16,(x,5.0*pi/6.0,pi),ylim=[-0.2,0.4],show=False)\nmyplot[0].line_color = 'r' #sin(t) is red\nmyplot[1].line_color = 'g' #U1 is green\nmyplot[2].line_color = 'b' #U2 is blue\nmyplot[3].line_color = 'c' #U3 is cyan\nmyplot[4].line_color = 'm' #U4 is magenta\nmyplot[5].line_color = 'y' #U5 is yellow\nmyplot[6].line_color = 'k' #U6 is black\nmyplot.show()","output":{"0":{"data":{"text/markdown":"<font color='red'>**Jupyter Kernel terminated:**</font> This might be caused by running out of memory or hitting a bug in some library (e.g., forking too many processes, trying to access invalid memory, etc.). Consider restarting or upgrading your project or running the relevant code directly in a terminal to track down the cause, as [explained here](https://github.com/sagemathinc/cocalc/wiki/KernelTerminated)."},"output_type":"execute_result","exec_count":0}},"cell_type":"code","exec_count":0}